version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: ping_global_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ping_data:/app/data
    ports:
      - "4888:4888"
    networks:
      - ping_network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: ping_global_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4887:4887"
    networks:
      - ping_network

networks:
  ping_network:
    driver: bridge

volumes:
  ping_data:
