FROM python:3.9-slim

WORKDIR /app

# 安装ping工具和其他依赖
RUN apt-get update && apt-get install -y iputils-ping && apt-get clean

# 先安装特定版本的Werkzeug
RUN pip install --no-cache-dir Werkzeug==2.0.3 Flask==2.0.1

# 复制依赖文件
COPY backend/requirements.txt .

# 安装其他依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用代码
COPY backend/ .

# 暴露端口
EXPOSE 4888

# 启动应用
CMD ["gunicorn", "--bind", "0.0.0.0:4888", "--log-level", "debug", "app:app"]
